[package]
name = "test-programs-artifacts"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]

[build-dependencies]
cargo_metadata.workspace = true
heck.workspace = true
